version: '3.8'

services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test1234
      POSTGRES_DB: test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
